### ISSUE TITLE
index.md

### ISSUE THREAD

**Issue by HienThuThiDai** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.fr-fr#1]
Current Translation:
Les liens hypertexte vers chaque exercice et démonstration de labo sont répertoriés ci-dessous.

Suggested Translation:
Les liens hypertexte vers chaque exercice de labo et chaque démo sont présentés ci-dessous.

Description:
As a general rule, please translate "demo" as "démo" and "demonstration" as "démonstration"

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Run bugfix tool and waiting for result.

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/184278067-2d7fde34-0a7c-450a-a121-8c54580ce007.png)
